### PR TITLE
fix: reassign cookies var to array if needed (fixes #8)

### LINKED ISSUE #8: Bug in Cookie._append
I found a weird bug affecting new visitors having no cookie at their first request (my project uses adonuxt ssr).

```
ERROR  cookies.map is not a function
  at Object.Cookie._append (/var/www/shared/node_modules/node-cookie/src/Cookie/index.js:164:39)
  at Object.Cookie.create (/var/www/shared/node_modules/node-cookie/src/Cookie/index.js:389:10)
  at Response.cookie (/var/www/shared/node_modules/@adonisjs/framework/src/Response/index.js:503:16)
```
And indeed, when you look at that line of code, you see that the `cookies` variable is not affected by the else-case of the ternary condition: 
https://github.com/poppinss/node-cookie/blob/07f12f663338069d7e2d07526bf795e5b3a24353/index.js#L162-L166

So, my quick workaround was to change it like so:
```javascript
  Array.isArray(cookies) ? cookies.push(cookie) : (cookies = [cookies]).push(cookie)
```
And it solved it. (I also changed the cookies declaration to `let` instead of `const`)

I don't know if you are comfortable with parenthesis assignment allowing to use directly the assigned value.

If so, I can make a PR to merge my fix into the lib. ;)

### PR DESCRIPTION
**Pull request by richie3366**
cf. #8

### CODE REVIEW

**Comment by thetutlage** [comment]
Would love to see a test that breaks the current code along with a test to fix it

**Comment by richie3366** [comment]
Sure.

Like I said in #8, it is probably due to Nuxt setting a cookie outside of Adonis, directly to the res object, without setting an array.

The test case will fail on `poppinss:develop` but will succeed on `Pickaw:cookies-patch`:
Screenshot at 13-39-32

Screenshot at 13-38-34

**Comment by HapLifeMan** [comment]
Any update @thetutlage?

**Comment by HapLifeMan** [comment]
Hey @thetutlage, can you take a look at this please?

**Pull request merged**
